### PR TITLE
update all dependencies

### PR DESCRIPTION
**Pull request by marcobiedermann**
Update dependencies

### CODE REVIEW

**Comment by drublic** [comment]
@marcobiedermann Can you please look at this again? Checks failed.

**Comment by dorgan** [comment]
I'll look at pulling ths in once we get the test task working again.  Please stand by...

**Comment by dorgan** [comment]
@marcobiedermann if you will update these to the latest current versions, I will go ahead and pull this in.  Thank you for contributing!

**Comment by dorgan** [comment]
@drublic his checked we're failing because of bad code already in the module. (see https://github.com/geddski/grunt-release/commit/7c52eef0080a94e9b1ac29997be56926561fa6e4?w=1)

**Comment by drublic** [comment]
Thanks for fixing this @dorgan.

**Comment by marcobiedermann** [comment]
@drublic @dorgan I've merged the updated `master` branch into my feature and updated all dependencies again. Hope, this will fit all your needs. If you got any more suggestions, feel free to hit me up :)

**Comment by dorgan** [comment]
@marcobiedermann looks like upgrading to latest dependencies breaks somethings as tests are failing.

**Comment by marcobiedermann** [comment]
@dorgan When I run `grunt test` I get the following output:
```
Running "setup:test" (setup) task
Warning: Path must be a string. Received [ 'test/fixtures/component.json' ] Use --force to continue.
```

Honestly I do not have any idea how to solve this. I googled a bit but could not find the right answer.

**Comment by dorgan** [comment]
I'm actually working through this now.  I've solved that problem as well as
another and now am working on the third, and then I believe there is a
fourth.  Hopefully I'll be able to get these resolved soon.

**Comment by dorgan** [comment]
Based on the complexities of the changes I am having to be compatible, this
will have to wait for the next release, as there will be breaking changes
in this.

**Comment by moczolaszlo** [comment]
Hi
I fixed the testes, all passed for me with the updated dependencies.
Tomorrow I will send a PR to this repo, ok?

**Comment by moczolaszlo** [comment]
Here: https://github.com/geddski/grunt-release/pull/156

**Comment by dorgan** [comment]
Resolved in #156

**Pull request closed without merging**
