### PR TITLE
Adding custom tasks

### LINKED ISSUE #6: Support custom tasks

### PR DESCRIPTION
**Pull request by mkay581**
Includes custom tasks. Resolves #6

### CODE REVIEW

**Comment by mkay581** [comment]
Rough concept, let me know what you all think. Always open to suggestions. :+1:

**Comment by drublic** [comment]
This looks very nice. Thanks so much, Mark.

Could you please have a look at the tests? Maybe you can write some for your code. I really want to improve coverage :)
Another point would be documentation. Please add the options to README.md.

This is super awesome.

**Comment by mkay581** [comment]
Thanks, I'm a big fan of test coverage so I will definitely create some tests! :) I just threw a few examples in the readme file. Did you want me to add them somewhere else also?

**Comment by cedricpinson** [comment]
Could you merge ? I am waiting for this feature :)

**Comment by drublic** [comment]
Thanks for the contribution. It landed now. New version will be available today.

**Comment by mkay581** [comment]
Cool. I'll see if I can get around to writing tests for it soon. Just been crazy busy. Glad to help!

**Pull request closed without merging**
