### PR TITLE
Fix for custom tasks

### PR DESCRIPTION
**Pull request by mkay581**
This fixes:

* So that `runTasks` returns a promise like all other methods
* Mixup with documentation vs. actual logic

### CODE REVIEW

**Comment by mkay581** [comment]
Team, please review and let me know if this is okay. I am navigating around to add a test in here somewhere. Is there a specific place you would like for me to put them?

**Comment by drublic** [comment]
Thanks for your work on this. I will test this better before merging it in this time ;)
You can put the tests into `test/release_test.js`.

**Comment by mkay581** [comment]
No problem. Yeah, definitely should have tests before merging :) I'll work on that in a bit. At work now.

**Comment by karol-f** [comment]
+1

**Comment by pmb0** [comment]
+1

**Pull request closed without merging**
